package keittokirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import keittokirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.16 11:33:48 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AinesTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi74 */
  @Test
  public void testRekisteroi74() {    // Aines: 74
    Aines a1 = new Aines(); 
    Aines a2 = new Aines(); 
    assertEquals("From: Aines line: 77", 0, a1.getRid()); 
    assertEquals("From: Aines line: 78", 0, a1.getAid()); 
    a1.rekisteroi(); 
    a2.rekisteroi(); 
    int n1 = a1.getRid(); 
    int n2 = a2.getRid(); 
    assertEquals("From: Aines line: 83", n2 - n1, n1); 
  } // Generated by ComTest END
}