package keittokirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import keittokirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.16 11:59:42 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ReseptitTest {


  // Generated by ComTest BEGIN
  /** 
   * testLisaa17 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa17() throws SailoException {    // Reseptit: 17
    Reseptit reseptit = new Reseptit(); 
    Resepti r1 = new Resepti(); 
    Resepti r2 = new Resepti(); 
    assertEquals("From: Reseptit line: 22", 0, reseptit.getLkm()); 
    reseptit.lisaa(r1); 
    reseptit.lisaa(r2); 
    assertEquals("From: Reseptit line: 25", 2, reseptit.getLkm()); 
    assertEquals("From: Reseptit line: 26", r1, reseptit.anna(0)); 
    assertEquals("From: Reseptit line: 27", r2, reseptit.anna(1)); 
  } // Generated by ComTest END
}