package keittokirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import keittokirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.16 11:36:44 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ReseptiTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi25 */
  @Test
  public void testRekisteroi25() {    // Resepti: 25
    Resepti r1 = new Resepti(); 
    assertEquals("From: Resepti line: 27", 0, r1.getTunnusNro()); 
    r1.rekisteroi(); 
    Resepti r2 = new Resepti(); 
    r2.rekisteroi(); 
    int n1 = r1.getTunnusNro(); 
    int n2 = r2.getTunnusNro(); 
    assertEquals("From: Resepti line: 33", n2-1, n1); 
  } // Generated by ComTest END
}