package keittokirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import keittokirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.16 11:38:57 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ValmistusohjeTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi46 */
  @Test
  public void testRekisteroi46() {    // Valmistusohje: 46
    Valmistusohje o1 = new Valmistusohje(); 
    assertEquals("From: Valmistusohje line: 48", 0, o1.getTunnusNro()); 
    o1.rekisteroi(); 
    Valmistusohje o2 = new Valmistusohje(); 
    o2.rekisteroi(); 
    int n1 = o1.getTunnusNro(); 
    int n2 = o2.getTunnusNro(); 
    assertEquals("From: Valmistusohje line: 54", n2-1, n1); 
  } // Generated by ComTest END
}